### ISSUE TITLE
Bundler could not find compatible versions for gem "autoextend"

### ISSUE THREAD

**Issue by edortigoza** [instructure/analytics#9]
hi I have this issue wiht latest version of canvas ruby 2.4.0  and bundler (1.13.6)
I try to find it https://rubygems.org/gems -  but can not find it,

Bundler could not find compatible versions for gem "autoextend":
  In Gemfile:
    analytics was resolved to 1.0.0, which depends on
      autoextend (~> 1.0.0)

Could not find gem 'autoextend (~> 1.0.0)', which is required by gem
'analytics', in any of the sources.

**Comment by ccutrer** [comment]
This sounds like you're trying to `bundle install` directly in analytics, which is not necessary. Just drop this repo into `gems/plugins/` within your `canvas-lms` checkout, and `bundle install` from the `canvas-lms` root, along with following the other install instructions for analytics.

The error is because the `autoextend` gem is provided by canvas, and _only_ by canvas, so it's impossible to find outside of the context of canvas.

**Comment by edortigoza** [comment]
Thanks...
